# Generated by Django 4.0.5 on 2022-10-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
